export const SETTING_POST_LOADING_TIMEOUT = 10000; // Time in milliseconds before considering a post loading failure
export const SETTING_POST_DEFAULT_EXPIRATION_DAYS = 30; // Default number of days for a post to be active
export const SETTING_POST_INITIAL_TAG_DISPLAY_LIMIT = 3; // Number of tags initially displayed on a post
export const SETTING_POST_HOT_SORT_RETROSPECTIVE_DAYS = 7; // Number of days to consider when sorting posts by 'hot'
export const SETTING_POST_MAX_CONTENT_LENGTH = 300; // Maximum allowed characters for a post's content
export const SETTING_POST_MAX_TAG_LENGTH = 20; // Maximum allowed characters for a tag
export const SETTING_POST_NEW_TAG_LIMIT = 5; // Maximum number of new tags allowed per post
export const SETTING_POST_MAX_POSTS_PER_HOUR = 10; // Maximum number of posts a user can create per hour
export const SETTING_POST_MAX_VOTES_PER_HOUR = 60; // Maximum number of votes a user can cast per hour
export const SETTING_HOOKS_TOAST_LIMIT = 1; // Maximum number of toasts to display at once
export const SETTING_HOOKS_TOAST_REMOVE_DELAY = 5000; // Delay in milliseconds before a toast automatically removes itself
export const SETTING_POST_PAGE_SIZE = 10; // Defines the number of items to fetch per page in data requests.
export const SETTING_POST_PREFETCH_DISTANCE = 10; // Defines how many pages ahead to prefetch data for smoother scrolling.
export const SETTING_POST_PINNED_CACHE_TTL = 60 * 60 * 1000; // Time To Live (TTL) for pinned posts cache in milliseconds (60 minutes)
